source "https://rubygems.org"

gem "rails", "~> 7.1.5"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "rack-cors"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.9"
gem "stripe", "~> 13.0"
gem "faraday", "~> 2.9"
gem "bootsnap", require: false
gem "dotenv-rails", groups: [:development, :test]

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
